# Generated by Django 5.1.4 on 2025-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectLine', models.CharField(max_length=64)),
                ('companyName', models.CharField(blank=True, max_length=64, null=True)),
                ('jobTitle', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
                ('jobLink', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(max_length=1024)),
                ('userID', models.IntegerField()),
                ('comments', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
